#ifndef _MAX_KEYDEFS_H_
#define _MAX_KEYDEFS_H_

/**	Bit mask values for various meta-key presses on the keyboard.
	@ingroup	jmouse	*/
typedef enum _modifiers {
	eCommandKey = 1,		///< Command Key
	eShiftKey = 2,			///< Shift Key
	eControlKey = 4,		///< Control Key
	eAltKey = 8,			///< Alt Key
	eLeftButton = 16,		///< Left mouse button
	eRightButton = 32,		///< Right mouse button
	eMiddleButton = 64,		///< Middle mouse button
	ePopupMenu = 128,		///< Popup Menu (contextual menu requested)
	eCapsLock = 256,		///< Caps lock
	eAutoRepeat = 512		///< Key is generated by key press auto-repeat
} t_modifiers;

// key codes
// key/keyup objects fourth outlet and key message to objects uses 
// the following values for keycodes
typedef enum _keycode {
	// keycode is ascii value with modifiers stripped
	// a-z keys thus report lowercase keycode regardless of shift key or capslock state
	JKEY_NONE		        = -1,
	JKEY_SPACEBAR           = -2,
	JKEY_ESC				= -3,
	JKEY_RETURN             = -4,
	JKEY_ENTER				= -4,  // same as JKEY_RETURN
	JKEY_TAB                = -5,
	JKEY_DELETE             = -6,
	JKEY_BACKSPACE          = -7,
	JKEY_INSERT             = -8,
	JKEY_UPARROW            = -9,
	JKEY_DOWNARROW          = -10,
	JKEY_LEFTARROW          = -11,
	JKEY_RIGHTARROW         = -12,
	JKEY_PAGEUP             = -13,
	JKEY_PAGEDOWN           = -14,
	JKEY_HOME               = -15,
	JKEY_END                = -16,
	JKEY_F1                 = -17,
	JKEY_F2                 = -18,
	JKEY_F3                 = -19,
	JKEY_F4                 = -20,
	JKEY_F5                 = -21,
	JKEY_F6                 = -22,
	JKEY_F7                 = -23,
	JKEY_F8                 = -24,
	JKEY_F9                 = -25,
	JKEY_F10                = -26,
	JKEY_F11                = -27,
	JKEY_F12                = -28,
	JKEY_F13                = -29,
	JKEY_F14                = -30,
	JKEY_F15                = -31,
	JKEY_F16                = -32,
	JKEY_NUMPAD0            = -33,
	JKEY_NUMPAD1            = -34,
	JKEY_NUMPAD2            = -35,
	JKEY_NUMPAD3            = -36,
	JKEY_NUMPAD4            = -37,
	JKEY_NUMPAD5            = -38,
	JKEY_NUMPAD6            = -39,
	JKEY_NUMPAD7            = -40,
	JKEY_NUMPAD8            = -41,
	JKEY_NUMPAD9            = -42,
	JKEY_NUMPADADD          = -43,
	JKEY_NUMPADSUBTRACT     = -44,
	JKEY_NUMPADMULTIPLY     = -45,
	JKEY_NUMPADDIVIDE       = -46,
	JKEY_NUMPADSEPARATOR    = -47,
	JKEY_NUMPADDECIMALPOINT = -48,
	JKEY_NUMPADEQUALS       = -49,
	JKEY_NUMPADDELETE       = -50,
	JKEY_PLAYPAUSE			= -51,
	JKEY_STOP				= -52,
	JKEY_NEXTTRACK			= -53,
	JKEY_PREVTRACK			= -54,
	JKEY_HELP				= -55
} t_keycode;


#endif // #ifndef _MAX_KEYDEFS_H_
