Max API: Miscellaneous Utility Module
Miscellaneous Utility Module
Jitter
Functions
float swapf32 (float f)
Byte swaps 32 bit floating point number.
double swapf64 (double f)
Byte swaps 64 bit floating point number.
void jit_global_critical_enter (void)
Enters the global Jitter critical region.
void jit_global_critical_exit (void)
Exits the global Jitter critical region.
void jit_error_sym (void *x, t_symbol *s)
Sends symbol based error message to Max console (safe from all threads)
void jit_error_code (void *x, t_jit_err v)
Sends error code based error message to Max console (safe from all threads)
void jit_post_sym (void *x, t_symbol *s)
Sends symbol based message to Max console (safe from all threads)
t_jit_err jit_err_from_max_err (t_max_err err)
Converts Max style error codes to Jitter style error codes.
void jit_rand_setseed (long n)
Sets global random number generator seed.
long jit_rand (void)
Generates a random value as a signed long integer.
Detailed Description
Function Documentation
jit_err_from_max_err()
t_jit_err jit_err_from_max_err (t_max_err err)
Converts Max style error codes to Jitter style error codes.
Parameters
err Max error code
Returns
t_jit_err error code
References MAX_ERR_DUPLICATE, MAX_ERR_GENERIC, MAX_ERR_INVALID_PTR, MAX_ERR_NONE, and MAX_ERR_OUT_OF_MEM.
Referenced by jit_attr_setchar_array(), jit_attr_setdouble_array(), jit_attr_setfloat(), jit_attr_setfloat_array(), jit_attr_setlong(), jit_attr_setlong_array(), jit_attr_setsym(), jit_attr_setsym_array(), jit_class_addadornment(), jit_class_addattr(), jit_class_addmethod(), jit_class_addtypedwrapper(), jit_class_free(), jit_class_method_addargsafe(), jit_class_register(), jit_object_detach(), jit_object_free(), and jit_object_unregister().
jit_error_code()
void jit_error_code (void * x, t_jit_err v)
Sends error code based error message to Max console (safe from all threads)
Parameters
x object pointer
v error code
References defer().
Referenced by max_jit_attr_getdump(), and max_jit_mop_jit_matrix().
jit_error_sym()
void jit_error_sym (void * x, t_symbol * s)
Sends symbol based error message to Max console (safe from all threads)
Parameters
x object pointer
s error message symbol
References defer().
jit_global_critical_enter()
void jit_global_critical_enter (void)
Enters the global Jitter critical region.
This function is useful for simple protection of thread sensitive operations. However, it may be too broad a lock, as it prevents any other operations that use the global critical region from working. For more localized control, I would suggest using either Max's systhread API or the platform specific locking mechanisms however, be sensitive to the possibility deadlock when locking code which calls code which may require the locking off unknown resources.
References critical_enter().
jit_global_critical_exit()
void jit_global_critical_exit (void)
Exits the global Jitter critical region.
This function is useful for simple protection of thread sensitive operations. However, it may be too broad a lock, as it prevents any other operations that use the global critical region from working. For more localized control, I would suggest using either Max's systhread API or the platform specific locking mechanisms however, be sensitive to the possibility deadlock when locking code which calls code which may require the locking off unknown resources.
References critical_exit().
jit_post_sym()
void jit_post_sym (void * x, t_symbol * s)
Sends symbol based message to Max console (safe from all threads)
Parameters
x object pointer
s message symbol
References defer().
jit_rand()
long jit_rand (void)
Generates a random value as a signed long integer.
Returns
random value
jit_rand_setseed()
void jit_rand_setseed (long n)
Sets global random number generator seed.
Parameters
n seed
References systime_ticks().
swapf32()
float swapf32 (float f)
Byte swaps 32 bit floating point number.
Parameters
f input float
Returns
byte swapped float
swapf64()
double swapf64 (double f)
Byte swaps 64 bit floating point number.
Parameters
f input double
Returns
byte swapped double