Max API
Operator Vector Module
Jitter
Functions
void jit_op_vector_pass_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: pass (char)
void jit_op_vector_mult_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: multiplication (char)
void jit_op_vector_div_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: division (char)
void jit_op_vector_mod_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: modulo (char)
void jit_op_vector_add_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: addition (char)
void jit_op_vector_adds_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: saturated addition (char)
void jit_op_vector_sub_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: subtraction (char)
void jit_op_vector_subs_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: saturated subtraction (char)
void jit_op_vector_min_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: minimum (char)
void jit_op_vector_max_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: maximum (char)
void jit_op_vector_avg_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: average (char)
void jit_op_vector_absdiff_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: absolute difference (char)
void jit_op_vector_pass_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: pass (float32)
void jit_op_vector_mult_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: multiplication (float32)
void jit_op_vector_div_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: division (float32)
void jit_op_vector_add_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: addition (float32)
void jit_op_vector_sub_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: subtraction (float32)
void jit_op_vector_min_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: minimum (float32)
void jit_op_vector_max_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: maximum (float32)
void jit_op_vector_abs_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: absolute value (float32)
void jit_op_vector_avg_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: average (float32)
void jit_op_vector_absdiff_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: absolute difference (float32)
void jit_op_vector_mod_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: modulo (float32)
void jit_op_vector_fold_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: fold (float32)
void jit_op_vector_wrap_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: wrap (float32)
void jit_op_vector_pass_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: pass (float64)
void jit_op_vector_mult_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: multiplication (float64)
void jit_op_vector_div_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: division (float64)
void jit_op_vector_add_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: addition (float64)
void jit_op_vector_sub_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: subtraction (float64)
void jit_op_vector_min_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: minimum (float64)
void jit_op_vector_max_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: maximum (float64)
void jit_op_vector_abs_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: absolute value (float64)
void jit_op_vector_avg_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: average (float64)
void jit_op_vector_absdiff_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: absolute difference (float64)
void jit_op_vector_mod_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: modulo (float64)
void jit_op_vector_fold_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: fold (float64)
void jit_op_vector_wrap_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: wrap (float64)
void jit_op_vector_pass_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: pass (long)
void jit_op_vector_mult_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: multiplication (long)
void jit_op_vector_div_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: division (long)
void jit_op_vector_mod_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: modulo (long)
void jit_op_vector_add_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: addition (long)
void jit_op_vector_sub_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: subtraction (long)
void jit_op_vector_min_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: minimum (long)
void jit_op_vector_max_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: maximum (long)
void jit_op_vector_abs_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: absolute value (long)
void jit_op_vector_avg_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: average (long)
void jit_op_vector_absdiff_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: absolute difference (long)
void jit_op_vector_bitand_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise and (char)
void jit_op_vector_bitor_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise or (char)
void jit_op_vector_bitxor_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise exclusive or (char)
void jit_op_vector_bitnot_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: bitwise not (char)
void jit_op_vector_rshift_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise right shift (char)
void jit_op_vector_lshift_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise left shift (char)
void jit_op_vector_bitand_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise and (long)
void jit_op_vector_bitor_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise or (long)
void jit_op_vector_bitxor_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise exclusive or (long)
void jit_op_vector_bitnot_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: bitwise not (long)
void jit_op_vector_rshift_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise right shift (long)
void jit_op_vector_lshift_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: bitwise left shift (long)
void jit_op_vector_flippass_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: flipped pass (char)
void jit_op_vector_flipdiv_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped division (char)
void jit_op_vector_flipmod_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped modulo (char)
void jit_op_vector_flipsub_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped subtraction (char)
void jit_op_vector_flippass_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: flipped pass (float32)
void jit_op_vector_flipdiv_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped division (float32)
void jit_op_vector_flipmod_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped modulo (float32)
void jit_op_vector_flipsub_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped subtraction (float32)
void jit_op_vector_flippass_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: flipped pass (float64)
void jit_op_vector_flipdiv_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped division (float64)
void jit_op_vector_flipmod_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped modulo (float64)
void jit_op_vector_flippass_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: flipped pass (long)
void jit_op_vector_flipdiv_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped division (long)
void jit_op_vector_flipmod_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped modulo (long)
void jit_op_vector_flipsub_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: flipped subtraction (long)
void jit_op_vector_and_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical and (char)
void jit_op_vector_or_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical or (char)
void jit_op_vector_not_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logical not (char)
void jit_op_vector_gt_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than (char)
void jit_op_vector_gte_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals (char)
void jit_op_vector_lt_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than (char)
void jit_op_vector_lte_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals (char)
void jit_op_vector_eq_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals (char)
void jit_op_vector_neq_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals (char)
void jit_op_vector_and_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical and (float32)
void jit_op_vector_or_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical or (float32)
void jit_op_vector_not_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logical not (float32)
void jit_op_vector_gt_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than (float32)
void jit_op_vector_gte_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals (float32)
void jit_op_vector_lt_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than (float32)
void jit_op_vector_lte_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals (float32)
void jit_op_vector_eq_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals (float32)
void jit_op_vector_neq_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals (float32)
void jit_op_vector_and_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical and (float64)
void jit_op_vector_or_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical or (float64)
void jit_op_vector_not_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logical not (float64)
void jit_op_vector_gt_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than (float64)
void jit_op_vector_gte_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals (float64)
void jit_op_vector_lt_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than (float64)
void jit_op_vector_lte_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals (float64)
void jit_op_vector_eq_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals (float64)
void jit_op_vector_neq_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals (float64)
void jit_op_vector_and_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical and (long)
void jit_op_vector_or_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: logical or (long)
void jit_op_vector_not_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logical not (long)
void jit_op_vector_gt_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than (long)
void jit_op_vector_gte_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals (long)
void jit_op_vector_lt_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than (long)
void jit_op_vector_lte_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals (long)
void jit_op_vector_eq_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals (long)
void jit_op_vector_neq_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals (long)
void jit_op_vector_gtp_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than pass (char)
void jit_op_vector_gtep_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals pass (char)
void jit_op_vector_ltp_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than pass (char)
void jit_op_vector_ltep_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals pass (char)
void jit_op_vector_eqp_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals pass (char)
void jit_op_vector_neqp_char (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals pass (char)
void jit_op_vector_gtp_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than pass (float32)
void jit_op_vector_gtep_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals pass (float32)
void jit_op_vector_ltp_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than pass (float32)
void jit_op_vector_ltep_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals pass (float32)
void jit_op_vector_eqp_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals pass (float32)
void jit_op_vector_neqp_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals pass (float32)
void jit_op_vector_gtp_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than pass (float64)
void jit_op_vector_gtep_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals pass (float64)
void jit_op_vector_ltp_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than pass (float64)
void jit_op_vector_ltep_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals pass (float64)
void jit_op_vector_eqp_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals pass (float64)
void jit_op_vector_neqp_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals pass (float64)
void jit_op_vector_gtp_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than pass (long)
void jit_op_vector_gtep_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: greater than or equals pass (long)
void jit_op_vector_ltp_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than pass (long)
void jit_op_vector_ltep_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: less than or equals pass (long)
void jit_op_vector_eqp_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: equals pass (long)
void jit_op_vector_neqp_long (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: not equals pass (long)
void jit_op_vector_sin_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: sine (float32)
void jit_op_vector_cos_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: cosine (float32)
void jit_op_vector_tan_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: tangent (float32)
void jit_op_vector_asin_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: arcsine (float32)
void jit_op_vector_acos_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: arccosine (float32)
void jit_op_vector_atan_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: arctangent (float32)
void jit_op_vector_atan2_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: arctangent (float32)
void jit_op_vector_sinh_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic sine (float32)
void jit_op_vector_cosh_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic cosine (float32)
void jit_op_vector_tanh_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic tangent (float32)
void jit_op_vector_asinh_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic arcsine (float32)
void jit_op_vector_acosh_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic arccosine (float32)
void jit_op_vector_atanh_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic arctangent (float32)
void jit_op_vector_exp_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: exponent (float32)
void jit_op_vector_exp2_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: exponent base 10 (float32)
void jit_op_vector_log_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logarithm (float32)
void jit_op_vector_log2_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logarithm base 2(float32)
void jit_op_vector_log10_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logarithm base 10 (float32)
void jit_op_vector_hypot_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: hypotenuse (float32)
void jit_op_vector_pow_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: power (float32)
void jit_op_vector_sqrt_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: square root (float32)
void jit_op_vector_ceil_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: ceiling (float32)
void jit_op_vector_floor_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: floor (float32)
void jit_op_vector_round_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: round (float32)
void jit_op_vector_trunc_float32 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: truncate (float32)
void jit_op_vector_sin_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: sine (float64)
void jit_op_vector_cos_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: cosine (float64)
void jit_op_vector_tan_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: tangent (float64)
void jit_op_vector_asin_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: arcsine (float64)
void jit_op_vector_acos_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: arccosine (float64)
void jit_op_vector_atan_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: arctangetn (float64)
void jit_op_vector_atan2_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: arctangent (float64)
void jit_op_vector_sinh_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic sine (float64)
void jit_op_vector_cosh_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic cosine (float64)
void jit_op_vector_tanh_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic tangent (float64)
void jit_op_vector_asinh_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic arcsine (float64)
void jit_op_vector_acosh_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic arccosine (float64)
void jit_op_vector_atanh_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: hyperbolic arctangent (float64)
void jit_op_vector_exp_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: exponent (float64)
void jit_op_vector_exp2_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: exponent base 2(float64)
void jit_op_vector_log_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logarithm (float64)
void jit_op_vector_log2_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logarithm base 2 (float64)
void jit_op_vector_log10_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: logarithm base 10 (float64)
void jit_op_vector_hypot_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: hypotenuse (float64)
void jit_op_vector_pow_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Binary operator: power (float64)
void jit_op_vector_sqrt_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: square root (float64)
void jit_op_vector_ceil_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: ceiling (float64)
void jit_op_vector_floor_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: floor (float64)
void jit_op_vector_round_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: round (float64)
void jit_op_vector_trunc_float64 (long n, void *vecdata, t_jit_op_info *in0, t_jit_op_info *in1, t_jit_op_info *out)
Unary operator: truncate (float64)
Detailed Description
Function Documentation
void jit_op_vector_abs_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: absolute value (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_abs_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: absolute value (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_abs_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: absolute value (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_absdiff_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: absolute difference (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_absdiff_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: absolute difference (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_absdiff_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: absolute difference (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_absdiff_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: absolute difference (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_acos_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: arccosine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_acos_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: arccosine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_acosh_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic arccosine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_acosh_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic arccosine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_add_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: addition (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_add_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: addition (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_add_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: addition (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_add_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: addition (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_adds_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: saturated addition (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_and_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical and (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_and_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical and (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_and_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical and (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_and_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical and (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_asin_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: arcsine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_asin_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: arcsine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_asinh_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic arcsine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_asinh_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic arcsine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_atan2_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: arctangent (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_atan2_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: arctangent (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_atan_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: arctangent (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_atan_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: arctangetn (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_atanh_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic arctangent (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_atanh_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic arctangent (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_avg_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: average (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_avg_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: average (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_avg_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: average (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_avg_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: average (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitand_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise and (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitand_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise and (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitnot_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: bitwise not (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitnot_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: bitwise not (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitor_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise or (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitor_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise or (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitxor_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise exclusive or (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_bitxor_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise exclusive or (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ceil_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: ceiling (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ceil_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: ceiling (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_cos_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: cosine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_cos_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: cosine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_cosh_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic cosine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_cosh_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic cosine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_div_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: division (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipdiv_char().
void jit_op_vector_div_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: division (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipdiv_float32().
void jit_op_vector_div_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: division (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipdiv_float64().
void jit_op_vector_div_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: division (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipdiv_long().
void jit_op_vector_eq_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_eq_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_eq_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_eq_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_eqp_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_eqp_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_eqp_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_eqp_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: equals pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_exp2_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: exponent base 10 (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_exp2_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: exponent base 2(float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_exp_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: exponent (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_exp_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: exponent (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_flipdiv_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped division (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_div_char().
void jit_op_vector_flipdiv_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped division (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_div_float32().
void jit_op_vector_flipdiv_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped division (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_div_float64().
void jit_op_vector_flipdiv_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped division (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_div_long().
void jit_op_vector_flipmod_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped modulo (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_mod_char().
void jit_op_vector_flipmod_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped modulo (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_mod_float32().
void jit_op_vector_flipmod_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped modulo (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_mod_float64().
void jit_op_vector_flipmod_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped modulo (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_mod_long().
void jit_op_vector_flippass_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: flipped pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_pass_char().
void jit_op_vector_flippass_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: flipped pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_pass_float32().
void jit_op_vector_flippass_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: flipped pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_pass_float64().
void jit_op_vector_flippass_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: flipped pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_pass_long().
void jit_op_vector_flipsub_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped subtraction (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_subs_char().
void jit_op_vector_flipsub_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped subtraction (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_sub_float32().
void jit_op_vector_flipsub_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: flipped subtraction (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References jit_op_vector_sub_long().
void jit_op_vector_floor_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: floor (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_floor_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: floor (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_fold_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: fold (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_fold_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: fold (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gt_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gt_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gt_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gt_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gte_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gte_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gte_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gte_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtep_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtep_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtep_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtep_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than or equals pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtp_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtp_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtp_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_gtp_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: greater than pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_hypot_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: hypotenuse (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_hypot_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: hypotenuse (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_log10_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logarithm base 10 (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_log10_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logarithm base 10 (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_log2_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logarithm base 2(float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_log2_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logarithm base 2 (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_log_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logarithm (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_log_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logarithm (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lshift_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise left shift (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lshift_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise left shift (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lt_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lt_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lt_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lt_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lte_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lte_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lte_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_lte_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltep_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltep_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltep_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltep_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than or equals pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltp_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltp_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltp_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_ltp_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: less than pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_max_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: maximum (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_max_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: maximum (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_max_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: maximum (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_max_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: maximum (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_min_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: minimum (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_min_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: minimum (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_min_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: minimum (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_min_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: minimum (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_mod_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: modulo (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipmod_char().
void jit_op_vector_mod_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: modulo (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipmod_float32().
void jit_op_vector_mod_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: modulo (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipmod_float64().
void jit_op_vector_mod_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: modulo (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipmod_long().
void jit_op_vector_mult_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: multiplication (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_mult_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: multiplication (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_mult_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: multiplication (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_mult_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: multiplication (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neq_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neq_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neq_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neq_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neqp_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neqp_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neqp_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_neqp_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: not equals pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_not_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logical not (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_not_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logical not (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_not_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logical not (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_not_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: logical not (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_or_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical or (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_or_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical or (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_or_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical or (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_or_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: logical or (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_pass_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: pass (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flippass_char().
void jit_op_vector_pass_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: pass (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flippass_float32().
void jit_op_vector_pass_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: pass (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
References t_jit_op_info::p, and t_jit_op_info::stride.
Referenced by jit_op_vector_flippass_float64().
void jit_op_vector_pass_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: pass (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flippass_long().
void jit_op_vector_pow_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: power (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_pow_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: power (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_round_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: round (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_round_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: round (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_rshift_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise right shift (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_rshift_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: bitwise right shift (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sin_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: sine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sin_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: sine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sinh_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic sine (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sinh_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic sine (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sqrt_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: square root (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sqrt_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: square root (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sub_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: subtraction (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sub_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: subtraction (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipsub_float32().
void jit_op_vector_sub_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: subtraction (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_sub_long (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: subtraction (long)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipsub_long().
void jit_op_vector_subs_char (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: saturated subtraction (char)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Referenced by jit_op_vector_flipsub_char().
void jit_op_vector_tan_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: tangent (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_tan_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: tangent (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_tanh_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic tangent (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_tanh_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: hyperbolic tangent (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_trunc_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: truncate (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_trunc_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Unary operator: truncate (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_wrap_float32 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: wrap (float32)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
void jit_op_vector_wrap_float64 (long n, void * vecdata, t_jit_op_info * in0, t_jit_op_info * in1, t_jit_op_info * out)
Binary operator: wrap (float64)
Parameters
n length of vectors
vecdata ignored
in0 left input pointer and stride
in1 right input pointer and stride
out output pointer and stride
Copyright © 2015, Cycling '74