Max API: Binary Module
Binary Module
Jitter
Functions
t_jit_err jit_bin_read_header (t_filehandle fh, t_uint32 *version, t_int32 *filesize)
Reads the header of a JXF binary file.
t_jit_err jit_bin_read_chunk_info (t_filehandle fh, t_uint32 *ckid, t_int32 *cksize)
Reads the the info of a chunk from a JXF binary file.
t_jit_err jit_bin_write_header (t_filehandle fh, t_int32 filesize)
Writes the header of a JXF binary file.
t_jit_err jit_bin_read_matrix (t_filehandle fh, void *matrix)
Reads matrix data from a JXF binary file.
t_jit_err jit_bin_write_matrix (t_filehandle fh, void *matrix)
Writes a matrix to a JXF binary file.
Detailed Description
Function Documentation
jit_bin_read_chunk_info()
t_jit_err jit_bin_read_chunk_info (t_filehandle fh, t_uint32 * ckid, t_int32 * cksize)
Reads the the info of a chunk from a JXF binary file.
Parameters
fh t_filehandle file handle
ckid chunk ID (ie JIT_BIN_CHUNK_CONTAINER, JIT_BIN_CHUNK_MATRIX)
cksize the size of the chunk
Returns
t_jit_err error code.
References SYSFILE_FROMMARK, sysfile_read(), and sysfile_setpos().
jit_bin_read_header()
t_jit_err jit_bin_read_header (t_filehandle fh, t_uint32 * version, t_int32 * filesize)
Reads the header of a JXF binary file.
Parameters
fh t_filehandle file handle
version version of the binary file format (ie JIT_BIN_VERSION_1)
filesize the size of the file
Returns
t_jit_err error code.
References SYSFILE_FROMSTART, sysfile_read(), and sysfile_setpos().
jit_bin_read_matrix()
t_jit_err jit_bin_read_matrix (t_filehandle fh, void * matrix)
Reads matrix data from a JXF binary file.
Parameters
fh t_filehandle file handle
matrix the matrix data
Returns
t_jit_err error code.
References _jit_sym_char, _jit_sym_float32, _jit_sym_float64, _jit_sym_getdata, _jit_sym_getinfo, _jit_sym_lock, _jit_sym_long, _jit_sym_setinfo, t_jit_matrix_info::dim, t_jit_matrix_info::dimcount, t_jit_matrix_info::flags, gensym(), JIT_MATRIX_MAX_DIMCOUNT, t_jit_matrix_info::planecount, sysfile_read(), and t_jit_matrix_info::type.
jit_bin_write_header()
t_jit_err jit_bin_write_header (t_filehandle fh, t_int32 filesize)
Writes the header of a JXF binary file.
Parameters
fh t_filehandle file handle
filesize the size of the file
Returns
t_jit_err error code.
References SYSFILE_FROMSTART, sysfile_setpos(), and sysfile_write().
jit_bin_write_matrix()
t_jit_err jit_bin_write_matrix (t_filehandle fh, void * matrix)
Writes a matrix to a JXF binary file.
Parameters
fh t_filehandle file handle
matrix the matrix data
Returns
t_jit_err error code.
References _jit_sym_char, _jit_sym_float32, _jit_sym_float64, _jit_sym_long, t_jit_matrix_info::dim, t_jit_matrix_info::dimcount, gensym(), JIT_MATRIX_MAX_DIMCOUNT, t_jit_matrix_info::planecount, sysfile_write(), and t_jit_matrix_info::type.