Max API: MOP Module
MOP Module
Jitter
Data Structures
struct t_jit_mop_io
t_jit_mop_io object struct.
struct t_jit_mop
t_jit_mop object struct.
Functions
t_jit_object * jit_mop_io_new (void)
Constructs instance of t_jit_mop_io.
t_jit_object * jit_mop_io_newcopy (t_jit_mop_io *x)
Constructs instance of t_jit_mop_io, copying settings of input.
t_jit_err jit_mop_io_free (t_jit_mop *x)
Frees instance of t_jit_mop_io.
t_jit_err jit_mop_io_restrict_type (t_jit_mop_io *x, t_jit_matrix_info *info)
Restricts the type specified in t_jit_matrix_info struct to those permitted by t_jit_mop_io instance, overwriting value in t_jit_matrix_info struct.
t_jit_err jit_mop_io_restrict_planecount (t_jit_mop_io *x, t_jit_matrix_info *info)
Restricts the planecount specified in t_jit_matrix_info struct to those permitted by t_jit_mop_io instance, overwriting value in t_jit_matrix_info struct.
t_jit_err jit_mop_io_restrict_dim (t_jit_mop_io *x, t_jit_matrix_info *info)
Restricts the dimension sizes specified in t_jit_matrix_info struct to those permitted by t_jit_mop_io instance, overwriting value in t_jit_matrix_info struct.
t_jit_err jit_mop_io_matrix (t_jit_mop_io *x, void *m)
Sets the internal matrix reference.
void * jit_mop_io_getmatrix (t_jit_mop_io *x)
Retrieves the internal matrix reference.
t_jit_err jit_mop_io_ioproc (t_jit_mop_io *x, method ioproc)
Sets the I/O procedure used when handling incoming matrices.
method jit_mop_io_getioproc (t_jit_mop_io *x)
Retrieves the I/O procedure used when handling incoming matrices.
t_jit_object * jit_mop_new (long inputcount, long outputcount)
Constructs instance of t_jit_mop.
t_jit_object * jit_mop_newcopy (t_jit_mop *x)
Constructs instance of t_jit_mop, copying settings of input.
void * jit_mop_getinput (t_jit_mop *x, long i)
Retrieves input at input list index specified.
void * jit_mop_getoutput (t_jit_mop *x, long i)
Retrieves output at output list index specified.
void * jit_mop_getinputlist (t_jit_mop *x)
Retrieves input list.
void * jit_mop_getoutputlist (t_jit_mop *x)
Retrieves output list.
t_jit_err jit_mop_free (t_jit_mop *x)
Frees instance of t_jit_mop.
t_jit_err jit_mop_single_type (void *mop, t_symbol *s)
Utility function to set the type attribute for all MOP inputs and outputs.
t_jit_err jit_mop_single_planecount (void *mop, long c)
Utility function to set the planecount attribute for all MOP inputs and outputs.
t_jit_err jit_mop_methodall (void *mop, t_symbol *s,...)
Utility function to send the same method to all MOP inputs and outputs.
t_jit_err jit_mop_input_nolink (void *mop, long c)
Utility function to disable all linking attributes for a MOP input.
t_jit_err jit_mop_output_nolink (void *mop, long c)
Utility function to disable all linking attributes for a MOP output.
t_jit_err jit_mop_ioproc_copy_adapt (void *mop, void *mop_io, void *matrix)
MOP I/O procedure to copy and adapt to input.
t_jit_err jit_mop_ioproc_copy_trunc (void *mop, void *mop_io, void *matrix)
MOP I/O procedure to copy, but truncate input.
t_jit_err jit_mop_ioproc_copy_trunc_zero (void *mop, void *mop_io, void *matrix)
MOP I/O procedure to copy, but truncate input.
t_symbol * jit_mop_ioproc_tosym (void *ioproc)
Utility to convert MOP I/O procedure function to a human-readable type name.
Detailed Description
Function Documentation
jit_mop_free()
t_jit_err jit_mop_free (t_jit_mop * x)
Frees instance of t_jit_mop.
Parameters
x t_jit_mop object pointer
Returns
t_jit_err error code
Warning
Use jit_object_free instead.
References t_jit_mop::inputlist, jit_object_free(), and t_jit_mop::outputlist.
jit_mop_getinput()
void * jit_mop_getinput (t_jit_mop * x, long i)
Retrieves input at input list index specified.
Parameters
x t_jit_mop object pointer
i index
Returns
t_jit_mop_io object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop.
References _jit_sym_getindex, and t_jit_mop::inputlist.
jit_mop_getinputlist()
void * jit_mop_getinputlist (t_jit_mop * x)
Retrieves input list.
Parameters
x t_jit_mop object pointer
Returns
t_jit_linklist object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop.
References t_jit_mop::inputlist.
jit_mop_getoutput()
void * jit_mop_getoutput (t_jit_mop * x, long i)
Retrieves output at output list index specified.
Parameters
x t_jit_mop object pointer
i index
Returns
t_jit_mop_io object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop.
References _jit_sym_getindex, and t_jit_mop::outputlist.
jit_mop_getoutputlist()
void * jit_mop_getoutputlist (t_jit_mop * x)
Retrieves output list.
Parameters
x t_jit_mop object pointer
Returns
t_jit_linklist object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop.
References t_jit_mop::outputlist.
jit_mop_input_nolink()
t_jit_err jit_mop_input_nolink (void * mop, long c)
Utility function to disable all linking attributes for a MOP input.
Parameters
mop t_jit_mop object pointer
c input index
Returns
t_jit_err error code
References _jit_sym_getindex, gensym(), t_jit_mop::inputlist, and jit_attr_setlong().
jit_mop_io_free()
t_jit_err jit_mop_io_free (t_jit_mop * x)
Frees instance of t_jit_mop_io.
Parameters
x t_jit_mop_io object pointer
Returns
t_jit_err error code
Warning
Use jit_object_free instead.
jit_mop_io_getioproc()
method jit_mop_io_getioproc (t_jit_mop_io * x)
Retrieves the I/O procedure used when handling incoming matrices.
Parameters
x t_jit_mop_io object pointer
Returns
I/O procedure
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
References t_jit_mop_io::ioproc.
jit_mop_io_getmatrix()
void * jit_mop_io_getmatrix (t_jit_mop_io * x)
Retrieves the internal matrix reference.
Parameters
x t_jit_mop_io object pointer
Returns
t_jit_matrix object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
References t_jit_mop_io::matrix.
jit_mop_io_ioproc()
t_jit_err jit_mop_io_ioproc (t_jit_mop_io * x, method ioproc)
Sets the I/O procedure used when handling incoming matrices.
Parameters
x t_jit_mop_io object pointer
ioproc I/O procedure
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
References t_jit_mop_io::ioproc.
jit_mop_io_matrix()
t_jit_err jit_mop_io_matrix (t_jit_mop_io * x, void * m)
Sets the internal matrix reference.
Parameters
x t_jit_mop_io object pointer
m t_jit_matrix object pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
References t_jit_mop_io::matrix.
jit_mop_io_new()
t_jit_object * jit_mop_io_new (void)
Constructs instance of t_jit_mop_io.
Returns
t_jit_mop_io object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References _jit_sym_char, _jit_sym_float32, _jit_sym_float64, _jit_sym_long, t_jit_mop_io::dimlink, gensym(), t_jit_mop_io::ioname, t_jit_mop_io::ioproc, JIT_MATRIX_MAX_DIMCOUNT, JIT_MATRIX_MAX_PLANECOUNT, t_jit_mop_io::matrix, t_jit_mop_io::matrixname, t_jit_mop_io::maxdim, t_jit_mop_io::maxdimcount, t_jit_mop_io::maxplanecount, t_jit_mop_io::mindim, t_jit_mop_io::mindimcount, t_jit_mop_io::minplanecount, t_jit_mop_io::planelink, t_jit_mop_io::special, t_jit_mop_io::typelink, t_jit_mop_io::types, and t_jit_mop_io::typescount.
jit_mop_io_newcopy()
t_jit_object * jit_mop_io_newcopy (t_jit_mop_io * x)
Constructs instance of t_jit_mop_io, copying settings of input.
Parameters
x t_jit_mop_io object pointer
Returns
t_jit_mop_io object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
jit_mop_io_restrict_dim()
t_jit_err jit_mop_io_restrict_dim (t_jit_mop_io * x, t_jit_matrix_info * info)
Restricts the dimension sizes specified in t_jit_matrix_info struct to those permitted by t_jit_mop_io instance, overwriting value in t_jit_matrix_info struct.
Parameters
x t_jit_mop_io object pointer
info t_jit_matrix_info pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
References t_jit_matrix_info::dim, t_jit_matrix_info::dimcount, JIT_MATRIX_MAX_DIMCOUNT, MAX, t_jit_mop_io::maxdim, t_jit_mop_io::maxdimcount, t_jit_mop_io::mindim, and t_jit_mop_io::mindimcount.
jit_mop_io_restrict_planecount()
t_jit_err jit_mop_io_restrict_planecount (t_jit_mop_io * x, t_jit_matrix_info * info)
Restricts the planecount specified in t_jit_matrix_info struct to those permitted by t_jit_mop_io instance, overwriting value in t_jit_matrix_info struct.
Parameters
x t_jit_mop_io object pointer
info t_jit_matrix_info pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
References t_jit_mop_io::maxplanecount, t_jit_mop_io::minplanecount, and t_jit_matrix_info::planecount.
jit_mop_io_restrict_type()
t_jit_err jit_mop_io_restrict_type (t_jit_mop_io * x, t_jit_matrix_info * info)
Restricts the type specified in t_jit_matrix_info struct to those permitted by t_jit_mop_io instance, overwriting value in t_jit_matrix_info struct.
Parameters
x t_jit_mop_io object pointer
info t_jit_matrix_info pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop_io.
References _jit_sym_type, jit_attr_getsym(), t_jit_mop_io::matrix, t_jit_matrix_info::type, t_jit_mop_io::types, and t_jit_mop_io::typescount.
jit_mop_ioproc_copy_adapt()
t_jit_err jit_mop_ioproc_copy_adapt (void * mop, void * mop_io, void * matrix)
MOP I/O procedure to copy and adapt to input.
Parameters
mop t_jit_mop object pointer
mop_io t_jit_mop_io object pointer
matrix t_jit_matrix object pointer
Returns
t_jit_err error code
void *m;
t_jit_matrix_info info;
if (matrix&&(m=jit_object_method(mop_io,_jit_sym_getmatrix))) {
    jit_object_method(matrix,_jit_sym_getinfo,&info);
    jit_object_method(mop_io,_jit_sym_restrict_type,&info);
    jit_object_method(mop_io,_jit_sym_restrict_dim,&info);
    jit_object_method(mop_io,_jit_sym_restrict_planecount,&info);
    jit_object_method(m,_jit_sym_setinfo,&info);
    jit_object_method(m,_jit_sym_frommatrix,matrix,NULL);
}
return JIT_ERR_NONE;
References _jit_sym_frommatrix, _jit_sym_getinfo, _jit_sym_getmatrix, _jit_sym_restrict_dim, _jit_sym_restrict_planecount, _jit_sym_restrict_type, and _jit_sym_setinfo.
Referenced by jit_mop_ioproc_tosym().
jit_mop_ioproc_copy_trunc()
t_jit_err jit_mop_ioproc_copy_trunc (void * mop, void * mop_io, void * matrix)
MOP I/O procedure to copy, but truncate input.
Parameters
mop t_jit_mop object pointer
mop_io t_jit_mop_io object pointer
matrix t_jit_matrix object pointer
Returns
t_jit_err error code
void *m;
t_jit_matrix_info info;
if (matrix&&(m=jit_object_method(mop_io,_jit_sym_getmatrix))) {
    jit_object_method(m,_jit_sym_frommatrix_trunc,matrix);
}
return JIT_ERR_NONE;
References _jit_sym_frommatrix_trunc, and _jit_sym_getmatrix.
Referenced by jit_mop_ioproc_tosym().
jit_mop_ioproc_copy_trunc_zero()
t_jit_err jit_mop_ioproc_copy_trunc_zero (void * mop, void * mop_io, void * matrix)
MOP I/O procedure to copy, but truncate input.
Zero elsewhere.
Parameters
mop t_jit_mop object pointer
mop_io t_jit_mop_io object pointer
matrix t_jit_matrix object pointer
Returns
t_jit_err error code
void *m;
t_jit_matrix_info info;
if (matrix&&(m=jit_object_method(mop_io,_jit_sym_getmatrix))) {
    jit_object_method(m,_jit_sym_clear);
    jit_object_method(m,_jit_sym_frommatrix_trunc,matrix);
}
return JIT_ERR_NONE;
References _jit_sym_clear, _jit_sym_frommatrix_trunc, and _jit_sym_getmatrix.
Referenced by jit_mop_ioproc_tosym().
jit_mop_ioproc_tosym()
t_symbol* jit_mop_ioproc_tosym (void * ioproc)
Utility to convert MOP I/O procedure function to a human-readable type name.
Parameters
ioproc t_jit_mop_io procedure pointer
Returns
t_symbol pointer
if (ioproc==NULL) {
return ps_resamp;
} else if (ioproc==jit_mop_ioproc_copy_adapt) {
return ps_adapt;
} else if (ioproc==jit_mop_ioproc_copy_trunc) {
return ps_trunc;
} else if (ioproc==jit_mop_ioproc_copy_trunc_zero) {
return ps_trunc_zero;
} else {
return ps_custom;
}
return ps_resamp;
References jit_mop_ioproc_copy_adapt(), jit_mop_ioproc_copy_trunc(), and jit_mop_ioproc_copy_trunc_zero().
jit_mop_methodall()
t_jit_err jit_mop_methodall (void * mop, t_symbol * s, ...)
Utility function to send the same method to all MOP inputs and outputs.
Parameters
mop t_jit_mop object pointer
s method symbol
... untyped arguments
Returns
t_jit_err error code
References _jit_sym_getindex, t_jit_mop::inputcount, t_jit_mop::inputlist, t_jit_mop::outputcount, and t_jit_mop::outputlist.
jit_mop_new()
t_jit_object * jit_mop_new (long inputcount, long outputcount)
Constructs instance of t_jit_mop.
Returns
t_jit_mop object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References _jit_sym_append, t_jit_mop::adapt, t_jit_mop::caninplace, gensym(), t_jit_mop::inputcount, t_jit_mop::inputlist, jit_attr_setsym(), jit_object_free(), t_jit_mop::outputcount, t_jit_mop::outputlist, t_jit_mop::outputmode, and t_jit_mop::special.
jit_mop_newcopy()
t_jit_object * jit_mop_newcopy (t_jit_mop * x)
Constructs instance of t_jit_mop, copying settings of input.
Parameters
x t_jit_mop object pointer
Returns
t_jit_mop object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_mop.
References _jit_sym_append, _jit_sym_getindex, _jit_sym_newcopy, gensym(), t_jit_mop::inputcount, t_jit_mop::inputlist, jit_object_free(), t_jit_mop::outputcount, and t_jit_mop::outputlist.
jit_mop_output_nolink()
t_jit_err jit_mop_output_nolink (void * mop, long c)
Utility function to disable all linking attributes for a MOP output.
Parameters
mop t_jit_mop object pointer
c output index
Returns
t_jit_err error code
References _jit_sym_getindex, gensym(), jit_attr_setlong(), and t_jit_mop::outputlist.
jit_mop_single_planecount()
t_jit_err jit_mop_single_planecount (void * mop, long c)
Utility function to set the planecount attribute for all MOP inputs and outputs.
Parameters
mop t_jit_mop object pointer
c planecount
Returns
t_jit_err error code
References _jit_sym_getindex, gensym(), t_jit_mop::inputcount, t_jit_mop::inputlist, jit_attr_setlong(), t_jit_mop::outputcount, and t_jit_mop::outputlist.
jit_mop_single_type()
t_jit_err jit_mop_single_type (void * mop, t_symbol * s)
Utility function to set the type attribute for all MOP inputs and outputs.
Parameters
mop t_jit_mop object pointer
s type symbol
Returns
t_jit_err error code
References _jit_sym_getindex, gensym(), t_jit_mop::inputcount, t_jit_mop::inputlist, jit_atom_setsym(), t_jit_mop::outputcount, and t_jit_mop::outputlist.