Max API
Attribute Module
Jitter
Data Structures
struct t_jit_attribute
t_jit_attribute object struct.
struct t_jit_attr_offset
t_jit_attr_offset object struct.
struct t_jit_attr_offset_array
t_jit_attr_offset_array object struct.
struct t_jit_attr_filter_clip
t_jit_attr_filter_clip object struct.
struct t_jit_attr_filter_proc
t_jit_attr_filter_proc object struct.
struct t_jit_attr
Common attribute struct.
Functions
t_symbol * jit_attr_getname (t_jit_attr *x)
Retrieves attribute name.
t_symbol * jit_attr_gettype (t_jit_attr *x)
Retrieves attribute type.
t_atom_long jit_attr_canget (t_jit_attr *x)
Retrieves attribute gettable flag.
t_atom_long jit_attr_canset (t_jit_attr *x)
Retrieves attribute settable flag.
t_atom_long jit_attr_usercanget (t_jit_attr *x)
Retrieves attribute user gettable flag.
t_atom_long jit_attr_usercanset (t_jit_attr *x)
Retrieves attribute user settable flag.
method jit_attr_getmethod (t_jit_attr *x, t_symbol *methodname)
Retrieves attribute getter or setter method.
t_jit_err jit_attr_filterget (t_jit_attr *x, void *y)
Sets attribute getter filter.
t_jit_err jit_attr_filterset (t_jit_attr *x, void *y)
Sets attribute setter filter.
t_jit_err jit_attr_get (t_jit_attr *x, void *parent, long *ac, t_atom **av)
Calls attribute getter to retrieve from parent object.
t_jit_err jit_attr_set (t_jit_attr *x, void *parent, long ac, t_atom *av)
Calls attribute setter to set in parent object.
t_jit_object * jit_attribute_new (char *name, t_symbol *type, long flags, method mget, method mset)
Constructs instance of t_jit_attribute.
t_jit_object * jit_attr_offset_new (char *name, t_symbol *type, long flags, method mget, method mset, long offset)
Constructs instance of t_jit_attr_offset.
t_jit_object * jit_attr_offset_array_new (char *name, t_symbol *type, long size, long flags, method mget, method mset, long offsetcount, long offset)
Constructs instance of t_jit_attr_offset_array.
t_jit_object * jit_attr_filter_clip_new (void)
Constructs instance of t_jit_attr_filter_clip.
t_jit_object * jit_attr_filter_proc_new (method proc)
Constructs instance of t_jit_attr_filter_proc.
t_atom_long jit_attr_getlong (void *x, t_symbol *s)
Retrieves attribute value as a long integer value.
t_jit_err jit_attr_setlong (void *x, t_symbol *s, t_atom_long c)
Sets attribute value as a long integer value.
t_atom_float jit_attr_getfloat (void *x, t_symbol *s)
Retrieves attribute value as a floating point value.
t_jit_err jit_attr_setfloat (void *x, t_symbol *s, t_atom_float c)
Sets attribute value as a floating point value.
t_symbol * jit_attr_getsym (void *x, t_symbol *s)
Retrieves attribute value as a symbol value.
t_jit_err jit_attr_setsym (void *x, t_symbol *s, t_symbol *c)
Sets attribute value as a symbol value.
long jit_attr_getlong_array (void *x, t_symbol *s, long max, t_atom_long *vals)
Retrieves attribute value as an array of long integer values.
t_jit_err jit_attr_setlong_array (void *x, t_symbol *s, long count, t_atom_long *vals)
Sets attribute value as an array of long integer values.
long jit_attr_getchar_array (void *x, t_symbol *s, long max, uchar *vals)
Retrieves attribute value as an array of char values.
t_jit_err jit_attr_setchar_array (void *x, t_symbol *s, long count, uchar *vals)
Sets attribute value as an array of char values.
long jit_attr_getfloat_array (void *x, t_symbol *s, long max, float *vals)
Retrieves attribute value as an array of floating point values.
t_jit_err jit_attr_setfloat_array (void *x, t_symbol *s, long count, float *vals)
Sets attribute value as an array of floating point values.
long jit_attr_getdouble_array (void *x, t_symbol *s, long max, double *vals)
Retrieves attribute value as an array of double precision floating point values.
t_jit_err jit_attr_setdouble_array (void *x, t_symbol *s, long count, double *vals)
Sets attribute value as an array of double precision floating point values.
long jit_attr_getsym_array (void *x, t_symbol *s, long max, t_symbol **vals)
Retrieves attribute value as an array of symbol values.
t_jit_err jit_attr_setsym_array (void *x, t_symbol *s, long count, t_symbol **vals)
Sets attribute value as an array of symbol values.
long jit_attr_symcompare (void *x, t_symbol *name)
Compares symbol name with name provided.
Detailed Description
Function Documentation
t_atom_long jit_attr_canget (t_jit_attr * x)
Retrieves attribute gettable flag.
Parameters
x attribute object pointer
Returns
gettable flag
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References t_jit_attr::flags, and JIT_ATTR_GET_OPAQUE.
t_atom_long jit_attr_canset (t_jit_attr * x)
Retrieves attribute settable flag.
Parameters
x attribute object pointer
Returns
settable flag
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References t_jit_attr::flags, and JIT_ATTR_SET_OPAQUE.
t_jit_object * jit_attr_filter_clip_new (void)
Constructs instance of t_jit_attr_filter_clip.
Returns
t_jit_attr_filter_clip object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References _jit_sym_float64, t_jit_attr_filter_clip::max, t_jit_attr_filter_clip::min, t_jit_attr_filter_clip::scale, t_jit_attr_filter_clip::type, t_jit_attr_filter_clip::usemax, t_jit_attr_filter_clip::usemin, and t_jit_attr_filter_clip::usescale.
t_jit_object * jit_attr_filter_proc_new (method proc)
Constructs instance of t_jit_attr_filter_proc.
Parameters
proc filter procedure
Returns
t_jit_attr_filter_clip object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References t_jit_attr_filter_proc::proc.
t_jit_err jit_attr_filterget (t_jit_attr * x, void * y)
Sets attribute getter filter.
Parameters
x attribute object pointer
y getter filter object
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References _jit_sym_filter, t_jit_attr::filterget, and jit_object_getmethod().
t_jit_err jit_attr_filterset (t_jit_attr * x, void * y)
Sets attribute setter filter.
Parameters
x attribute object pointer
y setter filter object
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References _jit_sym_filter, t_jit_attr::filterset, and jit_object_getmethod().
t_jit_err jit_attr_get (t_jit_attr * x, void * parent, long * ac, t_atom ** av)
Calls attribute getter to retrieve from parent object.
Parameters
x attribute object pointer
parent target object pointer
ac pointer to argument count
av pointer to argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References t_jit_attr::filterget, and t_jit_attr::get.
long jit_attr_getchar_array (void * x, t_symbol * s, long max, uchar * vals)
Retrieves attribute value as an array of char values.
Parameters
x object pointer
s attribute name
max maximum number of values to copy
vals pointer to retrieved values
Returns
number of values retrieved.
References object_attr_get(), and object_attr_getchar_array().
long jit_attr_getdouble_array (void * x, t_symbol * s, long max, double * vals)
Retrieves attribute value as an array of double precision floating point values.
Parameters
x object pointer
s attribute name
max maximum number of values to copy
vals pointer to retrieved values
Returns
number of values retrieved.
References object_attr_get(), and object_attr_getdouble_array().
t_atom_float jit_attr_getfloat (void * x, t_symbol * s)
Retrieves attribute value as a floating point value.
Parameters
x object pointer
s attribute name
Returns
floating point value
References object_attr_get(), and object_attr_getfloat().
long jit_attr_getfloat_array (void * x, t_symbol * s, long max, float * vals)
Retrieves attribute value as an array of floating point values.
Parameters
x object pointer
s attribute name
max maximum number of values to copy
vals pointer to retrieved values
Returns
number of values retrieved.
References object_attr_get(), and object_attr_getfloat_array().
t_atom_long jit_attr_getlong (void * x, t_symbol * s)
Retrieves attribute value as a long integer value.
Parameters
x object pointer
s attribute name
Returns
long integer value
References object_attr_get(), and object_attr_getlong().
Referenced by max_jit_classex_mop_wrap(), max_jit_mop_adapt_matrix_all(), max_jit_mop_clear(), max_jit_mop_free(), max_jit_mop_getoutputmode(), max_jit_mop_inputs(), max_jit_mop_jit_matrix(), max_jit_mop_matrix_args(), max_jit_mop_notify(), max_jit_mop_outputmatrix(), and max_jit_mop_outputs().
long jit_attr_getlong_array (void * x, t_symbol * s, long max, t_atom_long * vals)
Retrieves attribute value as an array of long integer values.
Parameters
x object pointer
s attribute name
max maximum number of values to copy
vals pointer to retrieved values
Returns
number of values retrieved.
References object_attr_get(), and object_attr_getlong_array().
method jit_attr_getmethod (t_jit_attr * x, t_symbol * methodname)
Retrieves attribute getter or setter method.
Parameters
x attribute object pointer
methodname "get" or "set" symbol
Returns
getter or setter method
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References _jit_sym_get, _jit_sym_set, t_jit_attr::filterget, t_jit_attr::filterset, t_jit_attr::get, and t_jit_attr::set.
t_symbol * jit_attr_getname (t_jit_attr * x)
Retrieves attribute name.
Parameters
x attribute object pointer
Returns
attribute name
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References _jit_sym_nothing, and t_jit_attr::name.
t_symbol* jit_attr_getsym (void * x, t_symbol * s)
Retrieves attribute value as a symbol value.
Parameters
x object pointer
s attribute name
Returns
symbol value
References object_attr_get(), and object_attr_getsym().
Referenced by jit_mop_io_restrict_type(), jit_ob3d_free(), jit_ob3d_new(), max_jit_classex_mop_wrap(), max_jit_mop_assist(), max_jit_mop_free(), max_jit_mop_notify(), max_jit_mop_outputmatrix(), max_jit_ob3d_attach(), and max_jit_ob3d_detach().
long jit_attr_getsym_array (void * x, t_symbol * s, long max, t_symbol ** vals)
Retrieves attribute value as an array of symbol values.
Parameters
x object pointer
s attribute name
max maximum number of values to copy
vals pointer to retrieved values
Returns
number of values retrieved.
References object_attr_get(), and object_attr_getsym_array().
t_symbol * jit_attr_gettype (t_jit_attr * x)
Retrieves attribute type.
Parameters
x attribute object pointer
Returns
attribute type
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References _jit_sym_nothing, and t_jit_attr::type.
t_jit_object * jit_attr_offset_array_new (char * name, t_symbol * type, long size, long flags, method mget, method mset, long offsetcount, long offset)
Constructs instance of t_jit_attr_offset_array.
Parameters
name attribute name
type data type
size maximum size
flags privacy flags
mget getter method
mset setter method
offsetcount byte offset to count struct member (if zero, remain fixed size with max size)
offset byte offset to array struct member
Returns
t_jit_attr_offset_array object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References t_jit_attr_offset_array::filterget, t_jit_attr_offset_array::filterset, t_jit_attr_offset_array::flags, gensym(), t_jit_attr_offset_array::get, t_jit_attr_offset_array::name, t_jit_attr_offset_array::offset, t_jit_attr_offset_array::offsetcount, t_jit_attr_offset_array::reserved, t_jit_attr_offset_array::set, t_jit_attr_offset_array::size, and t_jit_attr_offset_array::type.
t_jit_object * jit_attr_offset_new (char * name, t_symbol * type, long flags, method mget, method mset, long offset)
Constructs instance of t_jit_attr_offset.
Parameters
name attribute name
type data type
flags privacy flags
mget getter method
mset setter method
offset byte offset to struct member
Returns
t_jit_attr_offset object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References t_jit_attr_offset::filterget, t_jit_attr_offset::filterset, t_jit_attr_offset::flags, gensym(), t_jit_attr_offset::get, t_jit_attr_offset::name, t_jit_attr_offset::offset, t_jit_attr_offset::reserved, t_jit_attr_offset::set, and t_jit_attr_offset::type.
t_jit_err jit_attr_set (t_jit_attr * x, void * parent, long ac, t_atom * av)
Calls attribute setter to set in parent object.
Parameters
x attribute object pointer
parent target object pointer
ac argument count
av argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References t_jit_attr::filterset, and t_jit_attr::set.
t_jit_err jit_attr_setchar_array (void * x, t_symbol * s, long count, uchar * vals)
Sets attribute value as an array of char values.
Parameters
x object pointer
s attribute name
count number of values
vals pointer to values
Returns
t_jit_err error code.
References jit_err_from_max_err(), object_attr_get(), and object_attr_setchar_array().
t_jit_err jit_attr_setdouble_array (void * x, t_symbol * s, long count, double * vals)
Sets attribute value as an array of double precision floating point values.
Parameters
x object pointer
s attribute name
count number of values
vals pointer to values
Returns
t_jit_err error code.
References jit_err_from_max_err(), object_attr_get(), and object_attr_setdouble_array().
t_jit_err jit_attr_setfloat (void * x, t_symbol * s, t_atom_float c)
Sets attribute value as a floating point value.
Parameters
x object pointer
s attribute name
c value
Returns
t_jit_err error code.
References jit_err_from_max_err(), object_attr_get(), and object_attr_setfloat().
t_jit_err jit_attr_setfloat_array (void * x, t_symbol * s, long count, float * vals)
Sets attribute value as an array of floating point values.
Parameters
x object pointer
s attribute name
count number of values
vals pointer to values
Returns
t_jit_err error code.
References jit_err_from_max_err(), object_attr_get(), and object_attr_setfloat_array().
t_jit_err jit_attr_setlong (void * x, t_symbol * s, t_atom_long c)
Sets attribute value as a long integer value.
Parameters
x object pointer
s attribute name
c value
Returns
t_jit_err error code.
Referenced by jit_mop_input_nolink(), jit_mop_output_nolink(), jit_mop_single_planecount(), and max_jit_mop_matrix_args().
t_jit_err jit_attr_setlong_array (void * x, t_symbol * s, long count, t_atom_long * vals)
Sets attribute value as an array of long integer values.
Parameters
x object pointer
s attribute name
count number of values
vals pointer to values
Returns
t_jit_err error code.
References jit_err_from_max_err(), object_attr_get(), and object_attr_setlong_array().
t_jit_err jit_attr_setsym (void * x, t_symbol * s, t_symbol * c)
Sets attribute value as a symbol value.
Parameters
x object pointer
s attribute name
c value
Returns
t_jit_err error code.
References jit_err_from_max_err(), object_attr_get(), and object_attr_setsym().
Referenced by jit_matrix_exprfill(), jit_matrix_op(), jit_mop_new(), jit_ob3d_free(), jit_ob3d_new(), max_jit_mop_free(), max_jit_mop_inputs(), max_jit_mop_jit_matrix(), max_jit_mop_notify(), and max_jit_mop_outputs().
t_jit_err jit_attr_setsym_array (void * x, t_symbol * s, long count, t_symbol ** vals)
Sets attribute value as an array of symbol values.
Parameters
x object pointer
s attribute name
count number of values
vals pointer to values
Returns
t_jit_err error code.
References jit_err_from_max_err(), object_attr_get(), and object_attr_setsym_array().
long jit_attr_symcompare (void * x, t_symbol * name)
Compares symbol name with name provided.
Parameters
x attribute object pointer
name attribute name
Returns
1 if equal, 0 if not equal
References _jit_sym_getname, and object_method().
Referenced by max_jit_obex_attr_get(), and max_jit_obex_attr_set().
t_atom_long jit_attr_usercanget (t_jit_attr * x)
Retrieves attribute user gettable flag.
Parameters
x attribute object pointer
Returns
user gettable flag
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References t_jit_attr::flags, and JIT_ATTR_GET_OPAQUE_USER.
t_atom_long jit_attr_usercanset (t_jit_attr * x)
Retrieves attribute user settable flag.
Parameters
x attribute object pointer
Returns
user settable flag
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of any attribute obejct.
References t_jit_attr::flags, and JIT_ATTR_SET_OPAQUE_USER.
t_jit_object * jit_attribute_new (char * name, t_symbol * type, long flags, method mget, method mset)
Constructs instance of t_jit_attribute.
Parameters
name attribute name
type data type
flags privacy flags
mget getter method
mset setter method
Returns
t_jit_attribute object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References t_jit_attribute::data, t_jit_attribute::filterget, t_jit_attribute::filterset, t_jit_attribute::flags, gensym(), t_jit_attribute::get, t_jit_attribute::name, t_jit_attribute::reserved, t_jit_attribute::set, t_jit_attribute::size, and t_jit_attribute::type.
Copyright © 2015, Cycling '74