Max API: Linked List Module
Linked List Module
Jitter
Functions
void * jit_linklist_new (void)
Constructs instance of t_jit_linklist.
t_atom_long jit_linklist_getsize (t_jit_linklist *x)
Retrieves the linked list size.
void * jit_linklist_getindex (t_jit_linklist *x, long index)
Retrieves the object at the specified list index.
t_atom_long jit_linklist_objptr2index (t_jit_linklist *x, void *p)
Retrieves the list index for an object pointer.
t_atom_long jit_linklist_makearray (t_jit_linklist *x, void **a, long max)
Flatten the linked list into an array.
t_atom_long jit_linklist_insertindex (t_jit_linklist *x, void *o, long index)
Insert object at specified index.
t_atom_long jit_linklist_append (t_jit_linklist *x, void *o)
Append object to the end of the linked list.
t_atom_long jit_linklist_deleteindex (t_jit_linklist *x, long index)
Delete object at specified index, freeing the object.
t_atom_long jit_linklist_chuckindex (t_jit_linklist *x, long index)
Remove object at specified index, without freeing the object.
void jit_linklist_clear (t_jit_linklist *x)
Clears the linked list, freeing all objects in list.
void jit_linklist_chuck (t_jit_linklist *x)
Removes all objects from the linked list, without freeing any objects in list.
void jit_linklist_reverse (t_jit_linklist *x)
Reverses the order of objects in the linked list.
void jit_linklist_rotate (t_jit_linklist *x, long i)
Rotates the order of objects in the linked list, by the specified number of indeces.
void jit_linklist_shuffle (t_jit_linklist *x)
Randomizes the order of objects in the linked list.
void jit_linklist_swap (t_jit_linklist *x, long a, long b)
Swap list location of the indeces specified.
void jit_linklist_findfirst (t_jit_linklist *x, void **o, long cmpfn(void *, void *), void *cmpdata)
Retrieves the first object that satisfies the comparison function.
void jit_linklist_findall (t_jit_linklist *x, t_jit_linklist **out, long cmpfn(void *, void *), void *cmpdata)
Retrieves a linked list of all objects that satisfy the comparison function.
t_atom_long jit_linklist_findcount (t_jit_linklist *x, long cmpfn(void *, void *), void *cmpdata)
Retrieves the number of objects that satisfy the comparison function.
void jit_linklist_methodall (t_jit_linklist *x, t_symbol *s,...)
Calls a method on all objects in linked list.
void * jit_linklist_methodindex (t_jit_linklist *x, long i, t_symbol *s,...)
Calls a method on the object at the specified index.
void jit_linklist_sort (t_jit_linklist *x, long cmpfn(void *, void *))
Sorts linked list based on the provided comparison function.
Detailed Description
Function Documentation
jit_linklist_append()
t_atom_long jit_linklist_append (t_jit_linklist * x, void * o)
Append object to the end of the linked list.
Parameters
x t_jit_linklist object pointer
o object pointer
Returns
new list length, or -1 if unsuccessful
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_append().
Referenced by jit_matrix_op(), max_jit_classex_addattr(), and max_jit_obex_proxy_new().
jit_linklist_chuck()
void jit_linklist_chuck (t_jit_linklist * x)
Removes all objects from the linked list, without freeing any objects in list.
To remove all objects from the linked list, freeing the objects, use the jit_linklist_clear method.
Parameters
x t_jit_linklist object pointer
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_chuck().
Referenced by jit_matrix_op(), and jit_object_importattrs().
jit_linklist_chuckindex()
t_atom_long jit_linklist_chuckindex (t_jit_linklist * x, long index)
Remove object at specified index, without freeing the object.
This method will not free the object. To remove from the linked list and free the object, use the jit_linklist_deleteindex method.
Parameters
x t_jit_linklist object pointer
index index to remove (zero based)
Returns
index removed, or -1 if unsuccessful
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_chuckindex().
jit_linklist_clear()
void jit_linklist_clear (t_jit_linklist * x)
Clears the linked list, freeing all objects in list.
To remove all elements from the linked list without freeing the objects, use the jit_linklist_chuck method.
Parameters
x t_jit_linklist object pointer
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_clear().
jit_linklist_deleteindex()
t_atom_long jit_linklist_deleteindex (t_jit_linklist * x, long index)
Delete object at specified index, freeing the object.
To remove from the linked list without freeing the object, use the jit_linklist_chuckindex method.
Parameters
x t_jit_linklist object pointer
index index to delete (zero based)
Returns
index deleted, or -1 if unsuccessful
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_deleteindex().
jit_linklist_findall()
void jit_linklist_findall (t_jit_linklist * x, t_jit_linklist ** out, long cmpfnvoid *, void *, void * cmpdata)
Retrieves a linked list of all objects that satisfy the comparison function.
Parameters
x t_jit_linklist object pointer
out pointer to linked list containing all objects found found (set to NULL, if not found)
cmpfn comparison function pointer (should returns 1 if object matches data, otherwise 0)
cmpdata opaque data used in comparison function
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_findall().
jit_linklist_findcount()
t_atom_long jit_linklist_findcount (t_jit_linklist * x, long cmpfnvoid *, void *, void * cmpdata)
Retrieves the number of objects that satisfy the comparison function.
Parameters
x t_jit_linklist object pointer
cmpfn comparison function pointer (should returns 1 if object matches data, otherwise 0)
cmpdata opaque data used in comparison function
Returns
number object objects that satisfy the comparison function
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_chuck(), linklist_findall(), and linklist_getsize().
jit_linklist_findfirst()
void jit_linklist_findfirst (t_jit_linklist * x, void ** o, long cmpfnvoid *, void *, void * cmpdata)
Retrieves the first object that satisfies the comparison function.
Parameters
x t_jit_linklist object pointer
o pointer to object pointer found (set to NULL, if not found)
cmpfn comparison function pointer (should returns 1 if object matches data, otherwise 0)
cmpdata opaque data used in comparison function
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_findfirst().
Referenced by max_jit_obex_attr_get(), and max_jit_obex_attr_set().
jit_linklist_getindex()
void* jit_linklist_getindex (t_jit_linklist * x, long index)
Retrieves the object at the specified list index.
Parameters
x t_jit_linklist object pointer
index list index ()
Returns
object pointer
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_getindex().
Referenced by jit_object_importattrs().
jit_linklist_getsize()
t_atom_long jit_linklist_getsize (t_jit_linklist * x)
Retrieves the linked list size.
Parameters
x t_jit_linklist object pointer
Returns
linked list size
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_getsize().
Referenced by jit_object_importattrs().
jit_linklist_insertindex()
t_atom_long jit_linklist_insertindex (t_jit_linklist * x, void * o, long index)
Insert object at specified index.
Parameters
x t_jit_linklist object pointer
o object pointer
index index (zero based)
Returns
index inserted at, or -1 if unsuccessful
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_insertindex().
jit_linklist_makearray()
t_atom_long jit_linklist_makearray (t_jit_linklist * x, void ** a, long max)
Flatten the linked list into an array.
Parameters
x t_jit_linklist object pointer
a array pointer
max maximum array size
Returns
number of object pointers copied into array
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_makearray().
jit_linklist_methodall()
void jit_linklist_methodall (t_jit_linklist * x, t_symbol * s, ...)
Calls a method on all objects in linked list.
Equivalent to calling jit_object_method on the object at each index.
Parameters
x t_jit_linklist object pointer
s method name
... untyped arguments
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_methodall().
jit_linklist_methodindex()
void* jit_linklist_methodindex (t_jit_linklist * x, long i, t_symbol * s, ...)
Calls a method on the object at the specified index.
Equivalent to calling jit_object_method on the object.
Parameters
x t_jit_linklist object pointer
i index
s method name
... untyped arguments
Returns
method return value
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_methodindex().
jit_linklist_new()
void* jit_linklist_new (void)
Constructs instance of t_jit_linklist.
Returns
t_jit_linklist object pointer
Warning
While exported, it is recommend to use jit_object_new to construct a t_jit_linklist object.
References linklist_new().
Referenced by jit_matrix_op(), max_jit_classex_addattr(), and max_jit_obex_proxy_new().
jit_linklist_objptr2index()
t_atom_long jit_linklist_objptr2index (t_jit_linklist * x, void * p)
Retrieves the list index for an object pointer.
Parameters
x t_jit_linklist object pointer
p object pointer
Returns
object's list index (zero based), or -1 if not present
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_objptr2index().
jit_linklist_reverse()
void jit_linklist_reverse (t_jit_linklist * x)
Reverses the order of objects in the linked list.
Parameters
x t_jit_linklist object pointer
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_reverse().
jit_linklist_rotate()
void jit_linklist_rotate (t_jit_linklist * x, long i)
Rotates the order of objects in the linked list, by the specified number of indeces.
Parameters
x t_jit_linklist object pointer
i rotation index count
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_rotate().
jit_linklist_shuffle()
void jit_linklist_shuffle (t_jit_linklist * x)
Randomizes the order of objects in the linked list.
Parameters
x t_jit_linklist object pointer
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_shuffle().
jit_linklist_sort()
void jit_linklist_sort (t_jit_linklist * x, long cmpfnvoid *, void *)
Sorts linked list based on the provided comparison function.
Parameters
x t_jit_linklist object pointer
cmpfn comparison function pointer (returns 0 if a>b, otherwise 1)
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_sort().
jit_linklist_swap()
void jit_linklist_swap (t_jit_linklist * x, long a, long b)
Swap list location of the indeces specified.
Parameters
x t_jit_linklist object pointer
a index a
b index b
Warning
While exported, it is recommend to use jit_object_method to call methods on an object when the object may not be an instance of t_jit_linklist, but instead an object that supports some portion of the t_jit_linklist interface. One instance where this is the case is inside of a MOP matrix_calc method, where the arguments can be either an instance of t_jit_linklist, or t_jit_matrix which has a getindex method.
References linklist_swap().