Max API: Memory Module
Memory Module
Jitter
Functions
void * jit_getbytes (long size)
Allocates a pointer to memory.
void jit_freebytes (void *ptr, long size)
Frees a pointer to memory.
void ** jit_handle_new (long size)
Allocates a memory handle.
void jit_handle_free (void **handle)
Frees a memory handle.
long jit_handle_size_get (void **handle)
Retrieves a memory handle's size in bytes.
t_jit_err jit_handle_size_set (void **handle, long size)
Sets a memory handle's size in bytes.
long jit_handle_lock (void **handle, long lock)
Sets a memory handle's lock state.
void jit_copy_bytes (void *dest, const void *src, long bytes)
Copy bytes from source to destination pointer.
long jit_freemem (void)
Reports free memory.
char * jit_newptr (long size)
Allocates a pointer to memory.
void jit_disposeptr (char *ptr)
Frees a pointer to memory.
Detailed Description
Function Documentation
jit_copy_bytes()
void jit_copy_bytes (void * dest, const void * src, long bytes)
Copy bytes from source to destination pointer.
Parameters
dest destination pointer
src source pointer
bytes byte count to copy
References sysmem_copyptr().
jit_disposeptr()
void jit_disposeptr (char * ptr)
Frees a pointer to memory.
Warning
It is important to avoid mixing memory pools, and therefore to match calls to jit_newptr and jit_disposeptr.
Parameters
ptr pointer to memory
References sysmem_freeptr().
jit_freebytes()
void jit_freebytes (void * ptr, long size)
Frees a pointer to memory.
Depending on the size of the pointer, jit_freebytes will free from either the faster memory pool or the system memory pool.
Warning
It is important to avoid mixing memory pools, and therefore to match calls to jit_getbytes and jit_freebytes.
Parameters
ptr pointer to memory
size size in bytes allocated
References sysmem_freeptr().
Referenced by jit_matrix_freedata(), and max_jit_obex_free().
jit_freemem()
long jit_freemem (void)
Reports free memory.
Warning
Obsolete. OS 9 only.
Returns
free bytes
jit_getbytes()
void* jit_getbytes (long size)
Allocates a pointer to memory.
Depending on the size requested, jit_getbytes will allocate from either the faster memory pool or the system memory pool.
Warning
It is important to avoid mixing memory pools, and therefore to match calls to jit_getbytes and jit_freebytes.
Parameters
size size in bytes to allocate
Returns
pointer to memory
References sysmem_newptr().
Referenced by jit_matrix_getcell(), max_jit_classex_setup(), and max_jit_obex_new().
jit_handle_free()
void jit_handle_free (void ** handle)
Frees a memory handle.
Warning
It is important to avoid mixing memory pools, and therefore to match calls to jit_handle_new and jit_handle_free.
Parameters
handle memory handle
References sysmem_freehandle().
Referenced by jit_matrix_free().
jit_handle_lock()
long jit_handle_lock (void ** handle, long lock)
Sets a memory handle's lock state.
Parameters
handle memory handle
lock state (1=locked, 0=unlocked)
Returns
lock state.
References sysmem_lockhandle().
jit_handle_new()
void** jit_handle_new (long size)
Allocates a memory handle.
Handles are relocatable sections of memory which should be locked before dereferencing, and unlocked when not in use so that they may be relocated as necessary.
Warning
It is important to avoid mixing memory pools, and therefore to match calls to jit_handle_new and jit_handle_free.
Parameters
size size in bytes to allocate
Returns
memory handle
References sysmem_newhandle().
jit_handle_size_get()
long jit_handle_size_get (void ** handle)
Retrieves a memory handle's size in bytes.
Parameters
handle memory handle
Returns
size in bytes
References sysmem_handlesize().
jit_handle_size_set()
t_jit_err jit_handle_size_set (void ** handle, long size)
Sets a memory handle's size in bytes.
Parameters
handle memory handle
size new size in bytes
Returns
t_jit_err error code.
References sysmem_resizehandle().
jit_newptr()
char* jit_newptr (long size)
Allocates a pointer to memory.
Always allocates from the the system memory pool.
Warning
It is important to avoid mixing memory pools, and therefore to match calls to jit_newptr and jit_disposeptr.
Parameters
size size in bytes to allocate
Returns
pointer to memory
References sysmem_newptr().