Max API: Matrix Module
Matrix Module
Jitter
Functions
void jit_linklist_free (t_jit_linklist *x)
Frees instance of t_jit_linklist.
void * jit_matrix_new (t_jit_matrix_info *info)
Constructs instance of t_jit_matrix.
void * jit_matrix_newcopy (t_jit_matrix *copyme)
Constructs instance of t_jit_matrix, copying from input.
t_jit_err jit_matrix_free (t_jit_matrix *x)
Frees instance of t_jit_matrix.
t_jit_err jit_matrix_setinfo (t_jit_matrix *x, t_jit_matrix_info *info)
Sets all attributes according to the t_jit_matrix_info struct provided.
t_jit_err jit_matrix_setinfo_ex (t_jit_matrix *x, t_jit_matrix_info *info)
Sets all attributes according to the t_jit_matrix_info struct provided (including data flags).
t_jit_err jit_matrix_getinfo (t_jit_matrix *x, t_jit_matrix_info *info)
Retrieves all attributes, copying into the t_jit_matrix_info struct provided.
t_jit_err jit_matrix_getdata (t_jit_matrix *x, void **data)
Retrieves matrix data pointer.
t_jit_err jit_matrix_data (t_jit_matrix *x, void *data)
Sets matrix data pointer.
t_jit_err jit_matrix_freedata (t_jit_matrix *x)
Frees matrix's internal data pointer if an internal reference and sets to NULL.
t_jit_err jit_matrix_info_default (t_jit_matrix_info *info)
Initializes matrix info struct to default values.
t_jit_err jit_matrix_clear (t_jit_matrix *x)
Sets all cells in matrix to the zero.
t_jit_err jit_matrix_setcell1d (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets cell at index to the value provided.
t_jit_err jit_matrix_setcell2d (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets cell at index to the value provided.
t_jit_err jit_matrix_setcell3d (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets cell at index to the value provided.
t_jit_err jit_matrix_setplane1d (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets plane of cell at index to the value provided.
t_jit_err jit_matrix_setplane2d (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets plane of cell at index to the value provided.
t_jit_err jit_matrix_setplane3d (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets plane of cell at index to the value provided.
t_jit_err jit_matrix_setcell (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets cell at index to the value provided.
t_jit_err jit_matrix_getcell (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv, long *rac, t_atom **rav)
Gets cell at index to the value provided.
t_jit_err jit_matrix_setall (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets all cells to the value provided.
t_jit_err jit_matrix_fillplane (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Sets the plane specified in all cells to the value provided.
t_jit_err jit_matrix_frommatrix (t_jit_matrix *dst_matrix, t_jit_matrix *src_matrix, t_matrix_conv_info *mcinfo)
Copies Jitter matrix data from another matrix.
t_jit_err jit_matrix_op (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Applies unary or binary operator to matrix See Jitter user documentation for more information.
t_jit_err jit_matrix_exprfill (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Fills cells according to the jit.expr expression provided.
t_jit_err jit_matrix_jit_gl_texture (t_jit_matrix *x, t_symbol *s, long argc, t_atom *argv)
Copies texture information to matrix.
Detailed Description
Function Documentation
jit_linklist_free()
void jit_linklist_free (t_jit_linklist * x)
Frees instance of t_jit_linklist.
should never be called directly
Parameters
x t_jit_linklist object pointer
Returns
t_jit_err error code
Warning
Use jit_object_free instead.
References linklist_clear().
jit_matrix_clear()
t_jit_err jit_matrix_clear (t_jit_matrix * x)
Sets all cells in matrix to the zero.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
jit_matrix_data()
t_jit_err jit_matrix_data (t_jit_matrix * x, void * data)
Sets matrix data pointer.
Parameters
x t_jit_matrix object pointer
data data pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
jit_matrix_exprfill()
t_jit_err jit_matrix_exprfill (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Fills cells according to the jit.expr expression provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_float32, _jit_sym_frommatrix, _jit_sym_matrix_calc, _jit_sym_nothing, A_SYM, t_matrix_conv_info::flags, jit_atom_getlong(), jit_atom_getsym(), jit_attr_setsym(), jit_matrix_getinfo(), JIT_MATRIX_MAX_PLANECOUNT, jit_matrix_new(), jit_object_free(), t_jit_matrix_info::planecount, t_matrix_conv_info::planemap, and t_jit_matrix_info::type.
jit_matrix_fillplane()
t_jit_err jit_matrix_fillplane (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets the plane specified in all cells to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_char, _jit_sym_float32, _jit_sym_float64, _jit_sym_long, jit_atom_getcharfix(), jit_atom_getfloat(), and jit_atom_getlong().
jit_matrix_free()
t_jit_err jit_matrix_free (t_jit_matrix * x)
Frees instance of t_jit_matrix.
Parameters
x t_jit_matrix object pointer
Returns
t_jit_err error code
Warning
Use jit_object_free instead.
References jit_handle_free(), JIT_MATRIX_DATA_HANDLE, JIT_MATRIX_DATA_REFERENCE, and jit_matrix_freedata().
jit_matrix_freedata()
t_jit_err jit_matrix_freedata (t_jit_matrix * x)
Frees matrix's internal data pointer if an internal reference and sets to NULL.
Parameters
x t_jit_matrix object pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References jit_freebytes(), and JIT_MATRIX_DATA_REFERENCE.
Referenced by jit_matrix_free().
jit_matrix_frommatrix()
t_jit_err jit_matrix_frommatrix (t_jit_matrix * dst_matrix, t_jit_matrix * src_matrix, t_matrix_conv_info * mcinfo)
Copies Jitter matrix data from another matrix.
Parameters
dst_matrix destination t_jit_matrix object pointer
src_matrix destination t_jit_matrix object pointer
mcinfo conversion information pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_getdata, _jit_sym_getinfo, _jit_sym_lock, t_jit_matrix_info::dim, t_jit_matrix_info::dimcount, t_matrix_conv_info::dstdimend, t_matrix_conv_info::dstdimstart, t_matrix_conv_info::flags, JIT_MATRIX_CONVERT_DSTDIM, JIT_MATRIX_CONVERT_SRCDIM, JIT_MATRIX_MAX_DIMCOUNT, MAX, t_jit_matrix_info::size, t_matrix_conv_info::srcdimend, and t_matrix_conv_info::srcdimstart.
jit_matrix_getcell()
t_jit_err jit_matrix_getcell (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv, long * rac, t_atom ** rav)
Gets cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
rac return value atom count
rav return value atom vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_char, _jit_sym_float32, _jit_sym_float64, _jit_sym_long, _jit_sym_object, _jit_sym_symbol, _jit_sym_val, jit_atom_getlong(), jit_atom_setfloat(), jit_atom_setlong(), jit_atom_setobj(), jit_atom_setsym(), jit_getbytes(), and JIT_MATRIX_MAX_DIMCOUNT.
jit_matrix_getdata()
t_jit_err jit_matrix_getdata (t_jit_matrix * x, void ** data)
Retrieves matrix data pointer.
Parameters
x t_jit_matrix object pointer
data pointer to data pointer (set to NULL if matrix is not available)
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
jit_matrix_getinfo()
t_jit_err jit_matrix_getinfo (t_jit_matrix * x, t_jit_matrix_info * info)
Retrieves all attributes, copying into the t_jit_matrix_info struct provided.
Parameters
x t_jit_matrix object pointer
info t_jit_matrix_info pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
Referenced by jit_matrix_exprfill(), and jit_matrix_op().
jit_matrix_info_default()
t_jit_err jit_matrix_info_default (t_jit_matrix_info * info)
Initializes matrix info struct to default values.
Parameters
info t_jit_matrix_info struct pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References t_jit_matrix_info::dim, t_jit_matrix_info::dimcount, t_jit_matrix_info::dimstride, t_jit_matrix_info::flags, JIT_MATRIX_MAX_DIMCOUNT, t_jit_matrix_info::planecount, t_jit_matrix_info::size, and t_jit_matrix_info::type.
Referenced by jit_matrix_new(), max_jit_mop_inputs(), max_jit_mop_matrix_args(), and max_jit_mop_outputs().
jit_matrix_jit_gl_texture()
t_jit_err jit_matrix_jit_gl_texture (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Copies texture information to matrix.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_nothing, jit_atom_getsym(), jit_atom_setobj(), and jit_object_findregistered().
jit_matrix_new()
void * jit_matrix_new (t_jit_matrix_info * info)
Constructs instance of t_jit_matrix.
Parameters
info t_jit_matrix_info struct pointer
Returns
t_jit_matrix object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_new.
References t_jit_matrix_info::flags, JIT_MATRIX_DATA_FLAGS_USE, JIT_MATRIX_DATA_HANDLE, JIT_MATRIX_DATA_REFERENCE, jit_matrix_info_default(), and jit_object_free().
Referenced by jit_matrix_exprfill(), and jit_matrix_op().
jit_matrix_newcopy()
void * jit_matrix_newcopy (t_jit_matrix * copyme)
Constructs instance of t_jit_matrix, copying from input.
Parameters
copyme t_jit_matrix object pointer
Returns
t_jit_matrix object pointer
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References JIT_MATRIX_DATA_REFERENCE, and jit_object_free().
jit_matrix_op()
t_jit_err jit_matrix_op (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Applies unary or binary operator to matrix See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_class_jit_matrix, _jit_sym_matrix_calc, _jit_sym_nothing, A_FLOAT, A_LONG, A_OBJ, A_SYM, jit_atom_getsym(), jit_attr_setsym(), jit_linklist_append(), jit_linklist_chuck(), jit_linklist_new(), jit_matrix_getinfo(), jit_matrix_new(), jit_matrix_setall(), jit_object_findregistered(), jit_object_free(), and t_symbol::s_name.
jit_matrix_setall()
t_jit_err jit_matrix_setall (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets all cells to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_char, _jit_sym_float32, _jit_sym_float64, _jit_sym_long, jit_atom_getcharfix(), jit_atom_getfloat(), jit_atom_getlong(), and JIT_MATRIX_MAX_PLANECOUNT.
Referenced by jit_matrix_op().
jit_matrix_setcell()
t_jit_err jit_matrix_setcell (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_char, _jit_sym_float32, _jit_sym_float64, _jit_sym_long, _jit_sym_object, _jit_sym_plane, _jit_sym_symbol, _jit_sym_val, A_SYM, jit_atom_getcharfix(), jit_atom_getfloat(), jit_atom_getlong(), jit_atom_getobj(), jit_atom_getsym(), JIT_MATRIX_MAX_DIMCOUNT, and word::w_sym.
Referenced by jit_matrix_setcell1d(), jit_matrix_setcell2d(), jit_matrix_setcell3d(), jit_matrix_setplane1d(), jit_matrix_setplane2d(), and jit_matrix_setplane3d().
jit_matrix_setcell1d()
t_jit_err jit_matrix_setcell1d (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_val, jit_atom_getlong(), jit_atom_setlong(), jit_atom_setsym(), and jit_matrix_setcell().
jit_matrix_setcell2d()
t_jit_err jit_matrix_setcell2d (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_val, jit_atom_getlong(), jit_atom_setlong(), jit_atom_setsym(), and jit_matrix_setcell().
jit_matrix_setcell3d()
t_jit_err jit_matrix_setcell3d (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_val, jit_atom_getlong(), jit_atom_setlong(), jit_atom_setsym(), and jit_matrix_setcell().
jit_matrix_setinfo()
t_jit_err jit_matrix_setinfo (t_jit_matrix * x, t_jit_matrix_info * info)
Sets all attributes according to the t_jit_matrix_info struct provided.
Parameters
x t_jit_matrix object pointer
info t_jit_matrix_info pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_setinfo, and jit_object_notify().
Referenced by jit_matrix_setinfo_ex().
jit_matrix_setinfo_ex()
t_jit_err jit_matrix_setinfo_ex (t_jit_matrix * x, t_jit_matrix_info * info)
Sets all attributes according to the t_jit_matrix_info struct provided (including data flags).
Parameters
x t_jit_matrix object pointer
info t_jit_matrix_info pointer
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_modified, _jit_sym_nothing, t_jit_matrix_info::flags, JIT_MATRIX_DATA_REFERENCE, jit_matrix_setinfo(), jit_object_notify(), and t_jit_matrix_info::size.
jit_matrix_setplane1d()
t_jit_err jit_matrix_setplane1d (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets plane of cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_plane, _jit_sym_val, jit_atom_getlong(), jit_atom_setlong(), jit_atom_setsym(), and jit_matrix_setcell().
jit_matrix_setplane2d()
t_jit_err jit_matrix_setplane2d (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets plane of cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_plane, _jit_sym_val, jit_atom_getlong(), jit_atom_setlong(), jit_atom_setsym(), and jit_matrix_setcell().
jit_matrix_setplane3d()
t_jit_err jit_matrix_setplane3d (t_jit_matrix * x, t_symbol * s, long argc, t_atom * argv)
Sets plane of cell at index to the value provided.
See Jitter user documentation for more information.
Parameters
x t_jit_matrix object pointer
s message symbol pointer
argc argument count
argv argument vector
Returns
t_jit_err error code
Warning
This function is not exported, but is provided for reference when calling via jit_object_method on an intance of t_jit_matrix.
References _jit_sym_plane, _jit_sym_val, jit_atom_getlong(), jit_atom_setlong(), jit_atom_setsym(), and jit_matrix_setcell().